on: push
name: 🚀 Deploy medpocket api on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 103.211.202.141
          username: Dev-MedPocket
          password: ${{ secrets.ftp_password }}
          server-dir: prod-api.medpocket.in/

      - name: 📂 Sync files Stage
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 103.211.202.141
          username: Dev-MedPocket
          password: ${{ secrets.ftp_password }}
          server-dir: stage-api.medpocket.in/
